<?php 

?>

<?php 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info">
				<div class="style-1-icon info"></div>
				No data found.
	</div>

<?php
}
else
{ 
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; 
  // for edit and delete in view
$msgtitle = $this->controllername.'_delete';
sapp_Helper::editdeleteForView(EMPLOYMENTSTATUS,$this->controllername,$this->id,$msgtitle); ?>      
 <?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('nor','Work Code',$this->data['workcodename'],'Work Short Code',$this->data['workcode']);
sapp_Helper::viewBody('alt','Description',(!sapp_Helper::SappEmpty($this->data['description']))?$this->data['description']:"...",'','');
sapp_Helper::viewFooter();
?>
	<!-- <div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php //echo $this->controllername;?>',<?php //echo $this->id;?>);" value="Edit" />
			<button onclick="window.location.href='<?php //echo BASE_URL; ?>employmentstatus';" type="button" >Cancel</button>
		</div> -->
       
<?php	}	?>