<?php 

?>

<?php $baseUrl = $this->serverUrl().$this->baseUrl();
?>
<div id="error_message" style="display:none;"></div>
<div class="poc-ui-data-control">

		<?php echo $this->form->id; ?>
<?php 
$from_date = $this->form->from_date->getValue();
$to_date = $this->form->to_date->getValue();
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt',$this->form->educationlevel->getLabel(),(!empty($this->data[0]['educationlevel']))?$this->data[0]['educationlevel']:"...",'Institution Name',(!empty($this->data[0]['institution_name']))?$this->data[0]['institution_name']:"...");
sapp_Helper::viewBody('nor','Course',(!empty($this->data[0]['course']))?$this->data[0]['course']:"...",'From ',(!empty($from_date))?$this->form->from_date->getValue():"...");
sapp_Helper::viewBody('alt','To',(!empty($to_date))?$this->form->to_date->getValue():"...",'Percentage',(!empty($this->data[0]['percentage']))?$this->data[0]['percentage']:"...");
sapp_Helper::viewFooter();
?>
        <div class="new-form-ui-submit" id="formSubmit">
        <input onclick="closeiframepopup('educationdetails','cancel');" type="button" value="close"  />
        </div>
</div>      

