<?php 

?>

<?php if($this->rowexist !=''){?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
						No data found.
	</div>

<?php 
}else{
echo $this->form->id; ?>
<?php 
sapp_Helper::viewHeader();
$holiday_date = $this->form->holidaydate->getValue();
sapp_Helper::viewBody('alt','Holiday',(!empty($this->data['holidayname']))?$this->data['holidayname']:"...",'Date',(!empty($holiday_date))?$holiday_date:"...");
sapp_Helper::viewBody('nor','Description',(!empty($this->data['description']))?$this->data['description']:"...",'','');
sapp_Helper::viewFooter();
?>
        
			<div class="new-form-ui-submit">
            <input onclick="closeiframepopup('<?php echo $this->controllername;?>','cancel');" type="button"  value="Close"  />
		</div>
      
		
<?php } ?>		