<?php 

?>

<?php if($this->rowexist !=''){?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
						No data found.
	</div>

<?php 
}else{
echo $this->form->id; 
$msgtitle = $this->controllername.'_delete';
sapp_Helper::editdeleteForView(HOLIDAYDATES,$this->controllername,$this->id,$msgtitle); ?>
<?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Holiday',(!empty($this->data['holidayname']))?$this->data['holidayname']:"...",'Holiday Group',(!empty($this->data['groupid']))?$this->data['groupid']:"...");
$holiday_date = $this->form->holidaydate->getValue();
sapp_Helper::viewBody('nor','Date',(!empty($holiday_date))?$holiday_date:"...",'Description',(!empty($this->data['description']))?$this->data['description']:"...");
sapp_Helper::viewFooter();
?>
        
			<div class="new-form-ui-submit">
			<?php if(($this->editpermission == 'Yes')) { ?>
					<!-- <input type="submit" onclick="changeeditscreen('<?php echo $this->controllername;?>',<?php echo $this->id;?>);" value="Edit" />
					<button onclick="window.location.href='<?php echo BASE_URL; ?>holidaydates';" type="button" >Cancel</button> -->
		    <?php }
				   else{
		    ?>
					<input type="button" onclick="window.location.href='<?php echo BASE_URL; ?>holidaydates';" type="button"  value="Back"  />
    	    <?php } ?>
		</div>
       
<?php } ?>		
		