<?php

 ?>
<?php 

if($this->ermsg != '')
{
?>
<div class="ml-alert-1-info m1-info-set-2">
    <div class="style-1-icon info"></div>
       No data found.
</div>
<?php 
}
else
{
?>
		<?php
		if($this->previ_data == 'Yes')
		{
		?>
		<div class="new-form-ui-submit "  style="margin-top: 0px; float: right; width: auto; margin-left: 0px; ">
		   
				<?php             	
					$msgtitle = $this->controllername.'_delete';
					sapp_Helper::editdeleteForView(EXIT_PROC_SETTINGS,$this->controllername,$this->id,$msgtitle); 
				 ?>		
			
		</div>
		<?php 
		}
		?>

<?php sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Business Unit',(!empty( $this->data['unitname']))?  $this->data['unitname']:"...",'Department',(!empty($this->data['deptname']))?$this->data['deptname']:"...");

sapp_Helper::viewBody('nor','L2 Manager',(!empty($this->data['l2manager_userfullname']))? $this->data['l2manager_userfullname']:"...",'Hr Manager',(!empty($this->data['hrmanager_userfullname']))?$this->data['hrmanager_userfullname']:"...");

sapp_Helper::viewBody('alt','System Admin',(!empty($this->data['sysadmin_userfullname']))? $this->data['sysadmin_userfullname']:"...",'General Admin',(!empty($this->data['generaladmin_userfullname']))?$this->data['generaladmin_userfullname']:"...");

sapp_Helper::viewBody('nor','Finance Manager',(!empty($this->data['finacemanager_userfullname']))? $this->data['finacemanager_userfullname']:"...",'Notice Period',(!empty($this->data['notice_period']))?$this->data['notice_period']:"...");


sapp_Helper::viewFooter();

}//end of else
?>
