<?php 

?>

<?php if (count($this->messages)) {?>
	<div id="dispmsgpendingleaves" class="settingssuccess">
		<?php 
		foreach ($this->messages as $message)
			{
				$flag = array();				
				$flag = array_keys($message);
				echo "<div id='messageData' class='ml-alert-1-$flag[0]'><div style='display:block;'><span class='style-1-icon $flag[0]'></span>";
				echo $message[$flag[0]];
				echo "</div></div>";
			}
		?>
	</div>	
	
<?php } ?>

<?php if($this->call != 'ajaxcall'){ ?>
	<span id="error_message"></span>
<?php }?>
<?php 
echo sapp_Helper::displayLeaveTypeDiv($this->leavesCountArray); ?>
<?php 
if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->grid($this->dataArray[0]).$endDiv;

?>
<script type='text/javascript'>
$(document).ready(function(){
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispmsgpendingleaves').fadeOut('slow');
		},3000);

<?php } ?>

$('.count_new_dis').removeClass('count_new_dis_active');
<?php if(!empty($this->flag)) {?>
	$('#filter_<?php echo $this->flag;?>').addClass('count_new_dis_active');
<?php } else { ?>
	$('#filter_<?php echo $this->objName;?>').addClass('count_new_dis_active');
<?php } ?>
	if($('.count_new_dis_par').length>1) {
		$('.count_new_dis_par:first').remove();
		//$('.count_new_dis_par').not(':eq(0)').remove();
		$('.count_new_dis_par').insertAfter('#error_message');
	}
});
</script>

