<?php 

?>

    <?php if($this->rowexist !=''){?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
						Unauthorized access
	</div>


<?php 
}
else
{ ?>
<?php if($this->reportingmanagerStatus != 1) { 
	?>
    <div class="ml-alert-1-info">
	<div class="style-1-icon info"></div>   
    <?php
				if($this->reportingmanagerStatus == 0)
					echo "The Reporting manager of this employee is made inactive.";
				else if($this->reportingmanagerStatus == 2)
					echo "The Reporting manager of this employee has resigned the job.";
				else if($this->reportingmanagerStatus == 3)
					echo "The Reporting manager of this employee has left the organization.";
				else if($this->reportingmanagerStatus == 4)
					echo "The Reporting manager of this employee has been suspended.";
				else 
					echo "The Reporting manager of this employee deleted.";
	?>
    	</div>			
	<?php } ?>
<?php 

if(isset($_SESSION['emp_leaves']))
 {
	$back_str = '/'.$_SESSION['emp_leaves'];
	unset($_SESSION['emp_leaves']);
 }
 else 
 {
	$back_str = '';
	unset($_SESSION['emp_leaves']);
 }

$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; ?>
<?php 
    
sapp_Helper::viewHeader();
sapp_Helper::viewBody('nor','Available Leaves',$this->data['no_of_days'],'Reason',$this->data['reason']);
sapp_Helper::viewBody('alt','Leave Type',$this->data['leavetypeid'],'Leave',$this->form->leaveday->getValue());
sapp_Helper::viewBody('nor','From Date',$this->form->from_date->getValue(),'To Date',$this->form->to_date->getValue());
sapp_Helper::viewBody('alt','Status',$this->data['leavestatus'],'Number of Days',$this->form->appliedleavesdaycount->getValue());
sapp_Helper::viewBody('nor','Reporting Manager',$this->data['rep_mang_id'],'Applied On',$this->form->createddate->getValue());
sapp_Helper::viewFooter();
?> 
		<!--	<div class="new-form-ui-submit">
				<input onclick="window.location.href='<?php echo BASE_URL; ?>empleavesummary<?php echo $back_str;?>';" type="button"  value="back"  />
			</div> -->
<?php } ?>		