<?php 

?>

<?php 
		if($this->ermsg !='')
		{
?>
     <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				No data found.
	</div>

<?php 
}
else
{
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; 
$msgtitle = $this->controllername.'_delete';
sapp_Helper::editdeleteForView(STATES,$this->controllername,$this->id,$msgtitle);?>
<?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('nor','Country',$this->data[0]['countryid'],'State',$this->data[0]['state']);
sapp_Helper::viewFooter();
?>

		<!-- <div class="new-form-ui-submit">
            <input onclick="window.location.href='<?php //echo BASE_URL; ?>states';" type="button" value="Back" />
			</div> -->

<script type='text/javascript'>
 <?php if($this->stateValue!='') { ?>
	
			var stateval = '<?php echo $this->stateValue; ?>';
			var stateData = document.getElementById('state');
			for(var i = 0 ; i <= stateData.length ; i++)
			{
				if(stateData.options[i] !== undefined)
				{
					if (stateData.options[i].value == stateval) 
					{
						stateData.options[i].selected = true;
						break;
					}
				}
			}
			
	<?php } ?>	
</script>	

<?php } ?>	