<?php 

?>

<?php if($this->ermsg == 'nodata') { ?>
<div class="ml-alert-1-info m1-info-set"><div class="style-1-icon info"></div>No data found.</div>
<?php } else { ?>
<?php 
echo $this->form->id; ?>
<?php 
$groupId = $this->form->groupid->getValue();
$holidayDate = $this->form->holidaydate->getValue();
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Holiday',(!empty($this->data['holidayname']))?$this->data['holidayname']:"...",'Holiday Group',(!empty($groupId))?$this->form->groupid->getValue():"...");
sapp_Helper::viewBody('nor','Date',(!empty($holidayDate))?$this->form->holidaydate->getValue():"...",'Description',(!empty($this->data['description']))?$this->data['description']:"...");
sapp_Helper::viewFooter();
?>
        
		<div class="new-form-ui-submit">
        <!--<input onclick="window.location.href='<?php //echo BASE_URL; ?>myholidaycalendar';" type="submit"  value="Back" />--> 
		</div>
       
<?php } ?>