<?php 

?>

<?php if (count($this->messages)) {?>
	<div id="dispmsgempleave">
		  
	<?php foreach ($this->messages as $message){?>
		<?php if(!empty($message['deleteflag']) && $message['deleteflag']==1){?>
		
		<?php if($message['msgtype'] == 'error')
		{?>
			<div class="ml-alert-1-error">
	<div class="style-1-icon error"></div>
			<?php echo $message['error'];?>
			</div>
		<?php }else{ ?>
		<div class="ml-alert-1-success">
	<div class="style-1-icon success"></div>
			<?php echo $message['success'];?>
			</div>
		<?php }
		}else{
		?>
		<div class="ml-alert-1-success">
	<div class="style-1-icon success"></div>
		<?php echo $this->escape($message); ?>
	</div>
		<?php } 
	}?>
       
	</div>	
	
<?php } ?>
<span id="error_message"></span>
<?php 

if($this->call == 'ajaxcall'){
	$div = ''; $endDiv = ''; 
} else { 
	$div = '<div id="grid_'.$this->dataArray[0]['objectname'].'" class="all-grid-control">'; $endDiv = '</div>';
}
	echo $div.'<div id="msg" style="display:none;font-style: oblique; font-weight: bold; color: green;""></div>'.$this->grid($this->dataArray[0]).$endDiv;
?>

<script type='text/javascript'>
$(document).ready(function(){
<?php if (count($this->messages)) {?>
      setTimeout(function(){
			$('#dispmsgempleave').fadeOut('slow');
		},3000);

<?php } ?>

})
</script>

