<?php 

?>

<?php 
if($this->ermsg !='')
{
?>
     <div class="ml-alert-1-info">
				<div class="style-1-icon info"></div>
				No data found.
	</div>

<?php
}
else
{ 
$baseUrl = $this->serverUrl().$this->baseUrl();
echo $this->form->id; 
$msgtitle = $this->controllername.'_delete';
sapp_Helper::editdeleteForView(VENDORS,$this->controllername,$this->id,$msgtitle); ?>
<?php
 $name = $this->form->name->getValue();
 $country = $this->form->country->getValue();
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Name',(!empty($name))?$this->form->name->getValue():"...",'Contact Person',(!empty($this->data['contact_person']))?$this->data['contact_person']:"...");
sapp_Helper::viewBody('nor','Address',(!empty($this->data['address']))?$this->data['address']:"...",'Country',(!empty($country))?$this->form->country->getValue():"...");
sapp_Helper::viewBody('alt','State',(!empty($this->data['state']))?$this->data['state']:"...",'City ',(!empty($this->data['city']))?$this->data['city']:"...");
sapp_Helper::viewBody('nor','Pin Code',(!empty($this->data['pincode']))?$this->data['pincode']:"...",'Primary Phone',(!empty($this->data['primary_phone']))?$this->data['primary_phone']:"..."); 
sapp_Helper::viewBody('alt','Secondary Phone',(!empty($this->data['secondary_phone']))?$this->data['secondary_phone']:"...",'','');
sapp_Helper::viewFooter();
?>

       
	<!--	<div class="new-form-ui-submit">
			<input type="submit" onclick="changeeditscreen('<?php //echo $this->controllername;?>',<?php //echo $this->id;?>);" value="Edit" />
			<button onclick="window.location.href='<?php //echo BASE_URL; ?>vendors';" type="button" >Cancel</button>
		</div> -->
        
<?php	}	?>