<?php 

?>

<?php echo $this->form->id; 
		echo $this->form->user_id;
		?>
<?php 
$skill_last_used = $this->form->year_skill_last_used->getValue();
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Skill',(!empty($this->data['skillname']))?$this->data['skillname']:"...",'Years of Experience',(!empty($this->data['yearsofexp']))?$this->data['yearsofexp']:"...");
sapp_Helper::viewBody('nor','Competency Level',(!empty($this->data['competencylevelid']))?$this->data['competencylevelid']:"...",'Skill Last Used Year',(!empty($skill_last_used))?$this->form->year_skill_last_used->getValue():"...");
sapp_Helper::viewFooter();
?>
		 <div class="new-form-ui-submit" id="formSubmit">
         <input onclick="closeiframepopup('empskills','cancel');" type="button" value="Close"  />
        </div>
     
        