<?php 

?>

<?php if(empty($this->empdata)){?>
   <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				<?php if($this->rowexist == 'norows'){?>
						No data found.
				<?php }else{?>
						Employee inactivated.
				<?php }?>
	</div>

<?php 
}
else
{	
	if(!empty($this->employeedata))
	 {
			echo $this->employeedetails($this->employeedata,'edit',$this->id); 
	 } 
?>
<div class="right-block-data right-over-bottom-border"> 
	<div id="error_message" style="display:none;"></div>
		<!--<div class="ml-alert-1-info m1-info-set">-->
			<div style="margin-left: 0px; padding-top: 0px; padding-bottom: 20px;  float: none;" class="cofig_title">Assets
		</div>	
		 <div class="newtablegrid">
	 <table width="20%" cellspacing="0" cellpadding="0" border="0" class="grid">
      <?php 
		 if(count($this->userassetdata) > 0){
		 	$i = 0;
		 	?>   
       <thead>
       	<tr>
         <th align="center" >Asset Name</th>
         <th align="center" >Allocated Date</th>
       </tr>
       </thead>  
         <tbody>
         <?php 
		 	foreach($this->userassetdata as $user_asset){
    	  ?>
    	  <tr class="row1">
          <td align="right" ><?php echo $user_asset['name'];?></td>
		  <td align="right" ><?php echo sapp_Global::change_date($user_asset['created'],'view');?></td>
		  
        </tr>
         <?php }?> 
		 <?php 
		 $i++;
 		}else{	
 		?>
 		 <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
 					Assets not assigned yet.
 	     </div>				
        <?php }?> 
      </tbody>
  </table>
  </div>
</div>	
</div>
<script type="text/javascript" language="javascript">
$(document).ready(function() {
  
    $("#assetdetails").addClass('active');
	$("#assetdetails").removeAttr("onclick");

});//end of ready function

</script>
<?php 
}
?>

