<?php 

?>

<?php if(empty($this->data) || $this->data=='norows'){?>
     <div class="ml-alert-1-info">
		<div class="style-1-icon info"></div>
		<?php if($this->rowexist == 'norows'){?>
		No data found.
		<?php }else{?>
		No data found.
		<?php }?>
	</div>
<?php 
}
else
{
$data = $this->data;
$projectStatusArray = array('initiated'=>'Initiated','draft'=>'Draft','in-progress'=>'In Progress','hold'=>'Hold','completed'=>'Completed');

	?>
					

<div class="total-form-controller project_view_page"> 
	<div id="error_message" style="display:none;"></div>
	 <?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Project',(!empty($this->data[0]['project_name']))?$this->data[0]['project_name']:"...",'Client',(!empty($this->data[0]['client_name']))?$this->data[0]['client_name']:"...");
sapp_Helper::viewBody('nor','Description',(!empty($this->data[0]['description']))?$this->data[0]['description']:"...",'Currency',(!empty($this->data[0]['currencyname']))?$this->data[0]['currencyname']:"...");
sapp_Helper::viewBody('alt','Status',(!empty($projectStatusArray[$data[0]['project_status']]))?$projectStatusArray[$data[0]['project_status']]:"...",'Project Type',(!empty($this->data[0]['project_type']))?$this->data[0]['project_type']:"...");
sapp_Helper::viewBody('nor','Start Date',(!empty($this->data[0]['start_date']))?$this->data[0]['start_date']:"...",'End Date',(!empty($this->data[0]['end_date']))?$this->data[0]['end_date']:"..."); 
sapp_Helper::viewBody('alt','Estimated Hours ',(!empty($this->data[0]['estimated_hrs']))?$this->data[0]['estimated_hrs']:"...",'','');
sapp_Helper::viewFooter();
?>
    
		
</div>	

<div class="new-form-ui-submit">
			<input onclick="closeiframepopup('<?php echo $this->controllername; ?>','cancel');" type="button" value="Close" />
	
		</div>

<script type='text/javascript'>
$(document).ready(function(){
	$( "#tabs" ).tabs();
	 
	$('.breadcrumbs').append("<span class='arrows'>&rsaquo;</span><a href='<?php echo BASE_URL; ?>default/projects'>Projects</a><span class='arrows'>&rsaquo;</span><span>View</span>");
});
</script>
<?php } ?>