<?php 

?>

<?php if(empty($this->empdata)){?>
   <div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>
				<?php if($this->rowexist == 'norows'){?>
						No data found.
				<?php }else{?>
						Employee inactivated.
				<?php }?>
	</div>

<?php	}	else	{
sapp_Global::generateClientValidations($this->form);?>
<?php if(!empty($this->employeedata)) 
{
	echo $this->employeedetails($this->employeedata,'view',$this->id);
 } ?>

<div class="right-block-data"> 
	<div id="error_message" style="display:none;"></div>
<?php if(empty($this->data)){?>
			<div class="ml-alert-1-info m1-info-set">
				<div class="style-1-icon info"></div>Disability details are not configured yet.
			</div>
	<?php }else{?>	
	<?php echo $this->form->id; ?>


			<?php 
sapp_Helper::viewHeader();
sapp_Helper::viewBody('alt','Disability Type',(!empty($this->data[0]['disability_type']))?$this->data[0]['disability_type']:"...",'Disability',(!empty($this->data[0]['disability_name']))?$this->data[0]['disability_name']:"...");
sapp_Helper::viewBody('nor','Description/Reason',(!empty($this->data[0]['disability_description']))?$this->data[0]['disability_description']:"...",'','');
?>
<div class="new-form-ui" id="OtherdisabilityType" style="display:none;">
<?php 
sapp_Helper::viewBody('alt','Other Disability Type',(!empty($this->data[0]['other_disability_type']))?$this->data[0]['other_disability_type']:"...",'','');
sapp_Helper::viewFooter();
?>
				<div class="new-form-ui-submit">
				
				</div>
			</div>
			
<?php	}	?>
	
</div>
</div>

<script type="text/javascript" language="javascript">
$(document).ready(function() {
  var disabilityType = $("#disability_type").val();
	if(disabilityType !="" && disabilityType == "other impairments")
	{	
		showdisabilityField('disability_type');
	}
	
	$("#disabilitydetails").addClass('active');
	$("#disabilitydetails").removeAttr("onclick");

});//end of ready function

</script>
<?php	}	?>
